name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build controller image
      run: |
        make workflow-controller-image
        docker images
        make argocli-image
        docker images

    - name: Save Docker image to tar
      run: |
        # 方法2：从文件读取镜像列表
        echo "quay.io/argoproj/workflow-controller:latest" > image-list.txt
        echo "quay.io/argoproj/argocli:latest" >> image-list.txt
        docker save -o workflow-deploy.tar $(cat image-list.txt)

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: workflow-deploy-image
        path: workflow-deploy.tar
        retention-days: 3

